### ISSUE TITLE
Подключить линтера

### ISSUE THREAD

**Issue by dutchenkoOleg** [SergeevKirill/test1#3]
Статические анализаторы Eslint и Sass Lint
Конфиги смотрите в доках стажировки

**Comment by dutchenkoOleg** [comment]
Проверка "Исходного кода".  
Пример npm скриптов   
[![image](https://user-images.githubusercontent.com/16334642/53800818-45092a80-3f46-11e9-8ec1-e342a47f76c3.png)](https://user-images.githubusercontent.com/16334642/53800818-45092a80-3f46-11e9-8ec1-e342a47f76c3.png)

**Comment by dutchenkoOleg** [comment]
В идеале объединить в один   
[![image](https://user-images.githubusercontent.com/16334642/53800892-784bb980-3f46-11e9-9d62-0e1c01cfa043.png)](https://user-images.githubusercontent.com/16334642/53800892-784bb980-3f46-11e9-9d62-0e1c01cfa043.png)

**Comment by SergeevKirill** [comment]
Сделал
